[package]
name = "bench-serde-json"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[dependencies]
bencher = "0.1"
serde = "1.0"
serde_json = "1.0"

[profile.release]
lto = "fat"
codegen-units = 1
