[package]
name = "nom-json"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
nom = "^4.0"
#nom = {path = "/Users/geal/dev/rust/projects/nom" }
bencher = "0.1"
fnv = "1.0"
jemallocator = "0.1.8"

[profile.release]
lto = "fat"
codegen-units = 1
debug = true
