[package]
name = "combine-json"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
combine = "4.6.2"
bencher = "0.1"
fnv = "1.0"
jemallocator = "0.1.8"

[profile.release]
lto = "fat"
codegen-units = 1
