[package]
name = "nom-http"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
#nom = {git = "https://github.com/Geal/nom" }
nom = {path = "/Users/geal/dev/rust/projects/nom" }
bencher = "0.1"
stdsimd = "0.0.4"
