[package]
name = "pom-json"
version = "0.1.0"
authors = ["Eyal Kalderon <ebkalderon@gmail.com>"]

[dependencies]
bencher = "0.1"
fnv = "1.0"
jemallocator = "0.1.8"
pom = "3.0.2"

[profile.release]
lto = "fat"
codegen-units = 1
debug = true
